# Numpy:
    1. What is Numpy?
    2. what are Numpy arrays and how useful are they?
    3. How to use Numpy and create Numpy arrays?
    4. Basic and Universal functions on Numpy arrays
    5. Practice

### Numpy: 
> usually refered to as an abbreviation for *Numerical Python* and as the name suggests, it is a collection of functions and classes and methods grouped together for efficient mathemical computations.
> Numpy is not part of a Standard Library => that, it does not come with the general distribution of python and therefore has to be installed using the below command
```python
pip install numpy
```
> if you want to install the module from your *Jupyter Notebook* then the command is as follows:
```python
!pip install numpy
```

> Numpy library is actually a sub-set of another mighty library called as ***"Scipy"*** referred to as an abbreviation for *Scientific Python*

> To learn more about the libraries from the documentation

- [Numpy Documentation](https://docs.scipy.org/doc/numpy/user/quickstart.html)

- [Scipy Documentation](https://docs.scipy.org/doc/scipy/reference/)

#### Numpy Array:

> Numpy Arrays also called as *'ndarray'* is a powerful datastructure provided by Numpy library to work with homogeneous data.

> This *homogeneous* structuring contributes to the highly effective and efficient handling of the data in the structure.

> They are capable of handling multi-dimensional data.

#### Using Numpy

After successfully installing Numpy, we must first load the library to be able to use it and to do so, we need to type the command below:

```python
import numpy as np
```

*import* -> command used to load a library

*numpy* -> library name

*as* -> command to set an alias for the library being imported

*np* -> alias name for this project

In [ ]:
import numpy as np
np.__version__

'1.21.6'

### Creating an array

In [ ]:
a = [1, 2, 3, 4, 5]

b = np.array(a)

print(type(a), type(b))

<class 'list'> <class 'numpy.ndarray'>


In [ ]:
b.shape

(5,)

In [ ]:
b.dtype

dtype('int64')

### Basic Functions on Arrays

* reshape()
* arange()
* linspace()

In [ ]:
c = [1, 2, 3, 4, 5, 6]
d = np.array(c)
d.shape


(6,)

In [ ]:
d = d.reshape(2, 3)
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d = d.reshape(6, )

In [ ]:
d

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 2, 10)

array([1])

In [ ]:
np.linspace(1, 10, 100, dtype='int64')

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10])

# Universal Functions of Arrays
1. Addition
2. Multiplication
3. min()
4. max()

In [ ]:
c = [2, 4, 6, 8, 10]
d = np.array(c)
print(b + d)

[ 3  6  9 12 15]


In [ ]:
a + c

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

In [ ]:
PI = 3.14
print(b * PI)

[ 3.14  6.28  9.42 12.56 15.7 ]


In [ ]:
b, d

(array([1, 2, 3, 4, 5]), array([ 2,  4,  6,  8, 10]))

In [ ]:
b * d

In [ ]:
e = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
f = np.array([2, 4, 6, 8, 10, 12]).reshape(2, 3)

In [ ]:
e, f

(array([[1, 2, 3],
        [4, 5, 6]]), array([[ 2,  4,  6],
        [ 8, 10, 12]]))

In [ ]:
e @ f.T

array([[ 28,  64],
       [ 64, 154]])

In [ ]:
arr = np.dot(e, np.transpose(f))

In [ ]:
np.transpose(f)

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

In [ ]:
f.T

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

In [ ]:
np.min(arr)

28

In [ ]:
np.max(arr)

154

In [ ]:
np.average(arr)

77.5

In [ ]:
np.diagonal(arr)

array([ 28, 154])

In [ ]:
np.size(arr)

4

In [ ]:
arr.size

4

In [ ]:
arr1 = np.arange(1, 1501)

arr1 = arr1.reshape(150, 10)

In [ ]:
arr1

array([[   1,    2,    3, ...,    8,    9,   10],
       [  11,   12,   13, ...,   18,   19,   20],
       [  21,   22,   23, ...,   28,   29,   30],
       ...,
       [1471, 1472, 1473, ..., 1478, 1479, 1480],
       [1481, 1482, 1483, ..., 1488, 1489, 1490],
       [1491, 1492, 1493, ..., 1498, 1499, 1500]])

In [ ]:
arr1[1][1]

12

In [ ]:
arr1[20:30,2:7]

array([[203, 204, 205, 206, 207],
       [213, 214, 215, 216, 217],
       [223, 224, 225, 226, 227],
       [233, 234, 235, 236, 237],
       [243, 244, 245, 246, 247],
       [253, 254, 255, 256, 257],
       [263, 264, 265, 266, 267],
       [273, 274, 275, 276, 277],
       [283, 284, 285, 286, 287],
       [293, 294, 295, 296, 297]])

In [ ]:
arr2[0][0][4][1]

10

In [ ]:
arr2 = arr1.reshape(15, 10, 5, 2)
arr2

array([[[[   1,    2],
         [   3,    4],
         [   5,    6],
         [   7,    8],
         [   9,   10]],

        [[  11,   12],
         [  13,   14],
         [  15,   16],
         [  17,   18],
         [  19,   20]],

        [[  21,   22],
         [  23,   24],
         [  25,   26],
         [  27,   28],
         [  29,   30]],

        ...,

        [[  71,   72],
         [  73,   74],
         [  75,   76],
         [  77,   78],
         [  79,   80]],

        [[  81,   82],
         [  83,   84],
         [  85,   86],
         [  87,   88],
         [  89,   90]],

        [[  91,   92],
         [  93,   94],
         [  95,   96],
         [  97,   98],
         [  99,  100]]],


       [[[ 101,  102],
         [ 103,  104],
         [ 105,  106],
         [ 107,  108],
         [ 109,  110]],

        [[ 111,  112],
         [ 113,  114],
         [ 115,  116],
         [ 117,  118],
         [ 119,  120]],

        [[ 121,  122],
         [ 123,  124],
  

In [ ]:
b + 10

array([11, 12, 13, 14, 15])

In [ ]:
a = np.array([11, 2, 3, 21, 45, 9]).reshape(3, 2)

np.argmin(a, axis=1)


array([1, 0, 1])

In [ ]:
from numpy.linalg import inv

inv(a)

array([[-0.13934426,  0.20491803,  0.00819672],
       [ 1.44262295, -2.18032787,  0.03278689],
       [-0.58196721,  1.3852459 , -0.02459016]])

In [ ]:
a = np.array([1, 2, 3, 2, 1, 2, 89, 9, 1]).reshape(3, 3)
a

array([[ 1,  2,  3],
       [ 2,  1,  2],
       [89,  9,  1]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.ones((2, 4)) * 4
a.flatten()

array([4., 4., 4., 4., 4., 4., 4., 4.])

In [ ]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

print(a)
print(b)
np.concatenate((a, b), axis=1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
d

array([ 2,  4,  6,  8, 10])

In [ ]:
res = np.ones((4, 2)) * 5

In [ ]:
res.flatten()

array([5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.append, np.insert, np.delete, np.unique

# Pandas:

> Pandas is yet another Python library which is again not a part of the Standard Library and therefore requires installation

```python
pip install pandas
```

> Pandas provides a new datastructure called as *'Data Frames'* which is multi-dimensional and can be imagined to be something similar to that of the tables in databases or a sheet in the Excel / Spreadsheets and are *Highly Optimised*.

In [ ]:
import pandas as pd
pd.__version__

'1.3.5'

Name | Age
--- | ---
Chandra | 18
Arun | 17
Karen | 21

### Creating Dataframe

In [ ]:
example_dict = {"Name": ['Talentsprint', 'NPCI', 'Amazon'], "Address": ['Hyderabad', 'Mumbai', 'Bangalore']}

example_df = pd.DataFrame(example_dict)

type(example_df)

pandas.core.frame.DataFrame

In [ ]:
df = pd.read_csv('./Admission_Predict.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [ ]:
df.head(20)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0            1        337          118                  4  4.5   4.5  9.65   
1            2        324          107                  4  4.0   4.5  8.87   
2            3        316          104                  3  3.0   3.5  8.00   
3            4        322          110                  3  3.5   2.5  8.67   
4            5        314          103                  2  2.0   3.0  8.21   
5            6        330          115                  5  4.5   3.0  9.34   
6            7        321          109                  3  3.0   4.0  8.20   
7            8        308          101                  2  3.0   4.0  7.90   
8            9        302          102                  1  2.0   1.5  8.00   
9           10        323          108                  3  3.5   3.0  8.60   
10          11        325          106                  3  3.5   4.0  8.40   
11          12        327          111                  4  4.0   4.5  9.00   
12          13        328          112                  4  4.0   4.5  9.10   
13          14        307          109                  3  4.0   3.0  8.00   
14          15        311          104                  3  3.5   2.0  8.20   
15          16        314          105                  3  3.5   2.5  8.30   
16          17        317          107                  3  4.0   3.0  8.70   
17          18        319          106                  3  4.0   3.0  8.00   
18          19        318          110                  3  4.0   3.0  8.80   
19          20        303          102                  3  3.5   3.0  8.50   

    Research  Chance of Admit   
0          1              0.92  
1          1              0.76  
2          1              0.72  
3          1              0.80  
4          0              0.65  
5          1              0.90  
6          1              0.75  
7          0              0.68  
8          0              0.50  
9          0              0.45  
10         1              0.52  
11         1              0.84  
12         1              0.78  
13         1              0.62  
14         1              0.61  
15         0              0.54  
16         0              0.66  
17         1              0.65  
18         0              0.63  
19         0              0.62

In [ ]:
df.tail(10)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
390         391        314          102                  2  2.0   2.5  8.24   
391         392        318          106                  3  2.0   3.0  8.65   
392         393        326          112                  4  4.0   3.5  9.12   
393         394        317          104                  2  3.0   3.0  8.76   
394         395        329          111                  4  4.5   4.0  9.23   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
390         0              0.64  
391         0              0.71  
392         1              0.84  
393         0              0.77  
394         1              0.89  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95

In [ ]:
df.shape

(400, 9)

In [ ]:
df.min()

Serial No.             1.00
GRE Score            290.00
TOEFL Score           92.00
University Rating      1.00
SOP                    1.00
LOR                    1.00
CGPA                   6.80
Research               0.00
Chance of Admit        0.34
dtype: float64

In [ ]:
df.max()

Serial No.           400.00
GRE Score            340.00
TOEFL Score          120.00
University Rating      5.00
SOP                    5.00
LOR                    5.00
CGPA                   9.92
Research               1.00
Chance of Admit        0.97
dtype: float64

In [ ]:
df.std()

Serial No.           115.614301
GRE Score             11.473646
TOEFL Score            6.069514
University Rating      1.143728
SOP                    1.006869
LOR                    0.898478
CGPA                   0.596317
Research               0.498362
Chance of Admit        0.142609
dtype: float64

In [ ]:
df.mean()

Serial No.           200.500000
GRE Score            316.807500
TOEFL Score          107.410000
University Rating      3.087500
SOP                    3.400000
LOR                    3.452500
CGPA                   8.598925
Research               0.547500
Chance of Admit        0.724350
dtype: float64

In [ ]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [ ]:
sorted([11, 2, 32, 4, 54, 6, 7])

[2, 4, 6, 7, 11, 32, 54]

In [ ]:
import numpy as np

df['Research'][0] = np.nan
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0         NaN              0.92  
1         1.0              0.76  
2         1.0              0.72  
3         1.0              0.80  
4         0.0              0.65  
..        ...               ...  
395       1.0              0.82  
396       1.0              0.84  
397       1.0              0.91  
398       0.0              0.67  
399       1.0              0.95  

[400 rows x 9 columns]

In [ ]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  399.000000        400.000000  
mean     3.452500    8.598925    0.546366          0.724350  
std      0.898478    0.596317    0.498471          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           399 non-null    float64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(5), int64(4)
memory usage: 28.2 KB


In [ ]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             1
Chance of Admit      0
dtype: int64

In [ ]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [ ]:
df['GRE Score'].max()

340

In [ ]:
df['Research'].head()

0    1
1    1
2    1
3    1
4    0
Name: Research, dtype: int64

In [ ]:
df.Research

0      1
1      1
2      1
3      1
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Research, Length: 400, dtype: int64

In [ ]:
df['Research'].unique()

array([1, 0])

In [ ]:
df['University Rating'].nunique()

5

In [ ]:
# Categorical -> finite possibilities
# Continuous -> infinite possibilities

In [ ]:
df['GRE Score'].unique()

array([337, 324, 316, 322, 314, 330, 321, 308, 302, 323, 325, 327, 328,
       307, 311, 317, 319, 318, 303, 312, 334, 336, 340, 298, 295, 310,
       300, 338, 331, 320, 299, 304, 313, 332, 326, 329, 339, 309, 315,
       301, 296, 294, 306, 305, 290, 335, 333, 297, 293])

In [ ]:
df['GRE Score'].nunique()

49

In [ ]:
gre_score = df['GRE Score']
gre_score.mean()

316.8075

In [ ]:
gre_score.mode()

0    312
1    324
dtype: int64

In [ ]:
gre_score.median()

317.0

In [ ]:
df['Research'].value_counts()

1    219
0    181
Name: Research, dtype: int64

In [ ]:
df['University Rating'].value_counts()

3    133
2    107
4     74
5     60
1     26
Name: University Rating, dtype: int64

In [ ]:
gre_score

0      337
1      324
2      316
3      322
4      314
      ... 
395    324
396    325
397    330
398    312
399    333
Name: GRE Score, Length: 400, dtype: int64

In [ ]:
gre_score[210:221].unique()

array([325, 328, 338, 333, 331, 330, 322, 321, 324, 312, 313])

In [ ]:
data = {"Height": [1.75, 1.67, 1.8, 1.59, 1.74], "Weight": [72, 80, 50, 78, 71]}
data_df = pd.DataFrame(data)
data_df

Height  Weight
0    1.75      72
1    1.67      80
2    1.80      50
3    1.59      78
4    1.74      71

In [ ]:
data_df['BMI'] = data_df['Weight'] / np.square(data_df['Height'])

In [ ]:
data_df

Height  Weight        BMI
0    1.75      72  23.510204
1    1.67      80  28.685145
2    1.80      50  15.432099
3    1.59      78  30.853210
4    1.74      71  23.450918

In [ ]:
data1 = {"Height": [1.25, 1.37, 1.18, 1.95, 1.48], "Weight": [70, 81, 59, 111, 89]}
data_df2 = pd.DataFrame(data1)
data_df2['BMI'] = data_df2['Weight'] / np.square(data_df2['Height'])
data_df2

Height  Weight        BMI
0    1.25      70  44.800000
1    1.37      81  43.156268
2    1.18      59  42.372881
3    1.95     111  29.191321
4    1.48      89  40.631848

In [ ]:
data_df

Height  Weight        BMI
0    1.75      72  23.510204
1    1.67      80  28.685145
2    1.80      50  15.432099
3    1.59      78  30.853210
4    1.74      71  23.450918

In [ ]:
data_df2

Height  Weight        BMI
0    1.25      70  44.800000
1    1.37      81  43.156268
2    1.18      59  42.372881
3    1.95     111  29.191321
4    1.48      89  40.631848

In [ ]:
data_1 = {'id': [11, 21, 13, 14, 19, 24], 'name': ['Chandra', 'Arun', "Karen", 'Lissy', 'Carol', 'Manish']}
df1 = pd.DataFrame(data_1)
df1

id     name
0  11  Chandra
1  21     Arun
2  13    Karen
3  14    Lissy
4  19    Carol
5  24   Manish

In [ ]:
data_2 = {'id': [21, 11, 14, 13, 18, 20], 'marks': [89, 78, 65, 90, 76, 97]}
df2 = pd.DataFrame(data_2)
df2

id  marks
0  21     89
1  11     78
2  14     65
3  13     90
4  18     76
5  20     97

In [ ]:
pd.merge(df1, df2, on='id', how='right')

id     name  marks
0  21     Arun     89
1  11  Chandra     78
2  14    Lissy     65
3  13    Karen     90
4  18      NaN     76
5  20      NaN     97

In [ ]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left: 'DataFrame | Series', right: 'DataFrame | Series', how: 'str' = 'inner', on: 'IndexLabel | None' = None, left_on: 'IndexLabel | None' = None, right_on: 'IndexLabel | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool' = True, indicator: 'bool' = False, validate: 'str | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.
    
    A named Series object is treated as a DataFrame with a single named column.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.
    
    Parameters
    ----------
    left : DataFrame
  

In [ ]:
pd.merge()

In [ ]:
pd.concat([data_df, data_df2], axis=0)

Height  Weight        BMI
0    1.75      72  23.510204
1    1.67      80  28.685145
2    1.80      50  15.432099
3    1.59      78  30.853210
4    1.74      71  23.450918
0    1.25      70  44.800000
1    1.37      81  43.156268
2    1.18      59  42.372881
3    1.95     111  29.191321
4    1.48      89  40.631848

In [ ]:
df['GRE/TOEFL'] = df['GRE Score'] / df['TOEFL Score']
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   GRE/TOEFL  
0           1              0.92   2.855932  
1           1              0.76   3.028037  
2           1              0.72   3.038462  
3           1              0.80   2.927273  
4           0              0.65   3.048544  
..        ...               ...        ...  
395         1              0.82   2.945455  
396         1              0.84   3.037383  
397         1              0.91   2.844828  
398         0              0.67   3.029126  
399         1              0.95   2.846154  

[400 rows x 10 columns]

### Boolean Masks

In [ ]:
research_mask = df['Research'] == 1

df[~research_mask]

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
4             5        314          103                  2  2.0   3.0  8.21   
7             8        308          101                  2  3.0   4.0  7.90   
8             9        302          102                  1  2.0   1.5  8.00   
9            10        323          108                  3  3.5   3.0  8.60   
15           16        314          105                  3  3.5   2.5  8.30   
..          ...        ...          ...                ...  ...   ...   ...   
388         389        296           97                  2  1.5   2.0  7.80   
390         391        314          102                  2  2.0   2.5  8.24   
391         392        318          106                  3  2.0   3.0  8.65   
393         394        317          104                  2  3.0   3.0  8.76   
398         399        312          103                  3  3.5   4.0  8.78   

     Research  Chance of Admit  GRE/TOEFL  
4           0             0.65   3.048544  
7           0             0.68   3.049505  
8           0             0.50   2.960784  
9           0             0.45   2.990741  
15          0             0.54   2.990476  
..        ...              ...        ...  
388         0             0.49   3.051546  
390         0             0.64   3.078431  
391         0             0.71   3.000000  
393         0             0.77   3.048077  
398         0             0.67   3.029126  

[181 rows x 10 columns]

In [ ]:
df[~(df['GRE Score'] > 335)]

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
5             6        330          115                  5  4.5   3.0  9.34   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit  GRE/TOEFL  
1           1             0.76   3.028037  
2           1             0.72   3.038462  
3           1             0.80   2.927273  
4           0             0.65   3.048544  
5           1             0.90   2.869565  
..        ...              ...        ...  
395         1             0.82   2.945455  
396         1             0.84   3.037383  
397         1             0.91   2.844828  
398         0             0.67   3.029126  
399         1             0.95   2.846154  

[379 rows x 10 columns]

In [ ]:
df_filtered = df[(df['GRE Score'] > 335) & (df['TOEFL Score'] > 118) & (df['Chance of Admit'] >= 0.95)]
final_df = df_filtered[['GRE Score', 'TOEFL Score', 'Research', "Chance of Admit", "University Rating"]]
final_df

GRE Score  TOEFL Score  Research  Chance of Admit  University Rating
24         336          119         1             0.97                  5
81         340          120         1             0.96                  4
143        340          120         1             0.97                  4
202        340          120         1             0.97                  5
212        338          120         1             0.95                  4
372        336          119         1             0.95                  4

In [ ]:
df.columns = ['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit', 'GRE/TOEFL']

In [ ]:
final_df.to_csv('./Report.csv', index=False)

In [ ]:
df.drop(['Serial No.'], axis=1, inplace=True)

In [ ]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
395        324          110                  3  3.5   3.5  9.04         1   
396        325          107                  3  3.0   3.5  9.11         1   
397        330          116                  4  5.0   4.5  9.45         1   
398        312          103                  3  3.5   4.0  8.78         0   
399        333          117                  4  5.0   4.0  9.66         1   

     Chance of Admit  GRE/TOEFL  
0               0.92   2.855932  
1               0.76   3.028037  
2               0.72   3.038462  
3               0.80   2.927273  
4               0.65   3.048544  
..               ...        ...  
395             0.82   2.945455  
396             0.84   3.037383  
397             0.91   2.844828  
398             0.67   3.029126  
399             0.95   2.846154  

[400 rows x 9 columns]