## **Exercises**

#### Exercise 1: Import the numpy package under the name np

In [ ]:
import numpy as np

#### Exercise 2: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [ ]:
X = np.array([1, 45, 60, 90])

sin = np.sin(X)
cos = np.cos(X)
tan = np.tan(X)

print(sin)
print(cos)
print(tan)


[ 0.84147098  0.85090352 -0.30481062  0.89399666]
[ 0.54030231  0.52532199 -0.95241298 -0.44807362]
[ 1.55740772  1.61977519  0.32004039 -1.99520041]


#### Exercise 3: Given an array *X*. Convert angles from radians to degrees.

X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

In [ ]:
X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

degr = np.degrees(X)

print(degr)

[-180.  -90.   90.  180.]


#### Exercise 4: Given an arrya *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [ ]:
X = np.array([-180., -90., 90., 180.])

radi = np.radians(X)

print(radi)

[-3.14159265 -1.57079633  1.57079633  3.14159265]


#### Exercise 5: Given an array *X*. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of *X*, element-wise. 

X = np.array([-1., 0, 1.])

In [ ]:
X = np.array([-1., 0, 1.])

hyp_sin = np.sinh(X)
hyp_cos = np.cosh(X)
hyp_tan = np.tanh(X)

print(hyp_sin)
print(hyp_cos)
print(hyp_tan)

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


#### Exercise 6: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [ ]:
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

round = np.round(X)
ceil = np.ceil(X)
floor = np.floor(X)

print(round)
print(ceil)
print(floor)

[  4.   2.  44.  26.  -1. -10.  -7.]
[ 5.  3. 45. 26. -1. -9. -6.]
[  4.   2.  44.  25.  -2. -10.  -7.]


#### Exercise 7: Given an array *X*. Calculate the difference between neighboring elements, element-wise.

X = np.array([11, 13, 23, 45, 77])

In [ ]:
X = np.array([11, 13, 23, 45, 77])

neigh = np.diff(X)

print(neigh)

[ 2 10 22 32]


#### Exercise 8: Given two arrays *X* and *Y*. Find the cross product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

cross = np.cross(X, Y)

print(cross)

[-3  6 -3]


#### Exercise 9: Given two arrays *X* and *Y*. Find the dot product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

dot = np.dot(X, Y)

print(dot)

32


#### Exercise 10: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

div = np.divide(X, Y)
t_div = np.true_divide(X, Y)
f_div = np.floor_divide(X, Y)

print(div)
print(t_div)
print(f_div)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[0 0 0]


#### Exercise 11: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

com = np.power(X, Y)

print(com)

[  1  32 729]


#### Exercise 12: Given one array *X* and Y = 3. Compute the remainder of X / Y element-wise using remainder and fmod functions.


X = np.array([1, 2, 3])

In [ ]:
X = np.array([1, 2, 3])
Y = 3

comp = np.remainder(X, Y)
comp1 = np.fmod(X, Y)

print(comp)
print(comp1)

[1 2 0]
[1 2 0]


#### Exercise 13:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [ ]:
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
X1 = np.array([8, 4, 22, 3, 66, 12, 1, 5])

X[X < 5] = 4
X[X > 9] = 8

print(X1)
print(X)

[ 8  4 22  3 66 12  1  5]
[8 4 8 4 8 8 4 5]


#### Exercise 14: Given an array *X*. Compute the square of *X*, element-wise.

X = np.array([2, 3, 4, 5, 6])

In [ ]:
X = np.array([2, 3, 4, 5, 6])

squ = np.square(X)

print(squ)

[ 4  9 16 25 36]


#### Exercise 15: Given an array *X*. Compute the absolute value of *X*.

X = np.array([[-44, 3], [4, -3]])

In [ ]:
X = np.array([[-44, 3], [4, -3]])

abs = np.absolute(X)

print(abs)

[[44  3]
 [ 4  3]]


#### Exercise 16: Given an array *X*. Compute an element-wise indication of the sign of *X*, element-wise.

X = np.array([1, 3, 0, -1, -3])

In [ ]:
X = np.array([1, 3, 0, -1, -3])

indi = np.sign(X)

print(indi)

[ 1  1  0 -1 -1]


#### Exercise 17: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
np.random.randn(0,1)

array([], shape=(0, 1), dtype=float64)

#### Exercise 18: Given an array *gaussian*. How do you get the number of dimensions of the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

print(gaussian.ndim)

3


#### Exercise 19: Given an array *gaussian*. How do you get the shape of an array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

print(gaussian.shape)

(2, 3, 4)


#### Exercise 20: Given an array *gaussian*. How do you get the total number of elements in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

print(gaussian.size)

24


#### Exercise 21: Given an array *gaussian*. How do you get memory consumed by each item in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

print(gaussian.itemsize) # Each Item Consumed
print(gaussian.size * gaussian.itemsize) # Total Consumed

8
192


#### Exercise 22: Given an array *twenty*. How do you access first two rows and three columns

twenty = (np.arange(4 * 5)).reshape(4, 5)

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)

row_colm = twenty[0:2, 0:3]

print(row_colm)

[[0 1 2]
 [5 6 7]]


#### Exercise 23: Given an array *twenty*. How do you reverse the order of elements along columns?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)

col = np.flip(twenty, 1)

print(col)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


#### Exercise 24: Given an array *twenty*. How do you reverse the order of elements along rows?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)

col1 = np.flip(twenty, 0)

print(col1)

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


#### Exercise 25: Given an array *twenty*. How do you shuffle the array along axis - 0


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)

np.random.shuffle(twenty[0])

twenty

array([[ 4,  1,  2,  3,  0],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])